name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: browser-genai-eval       # Clean, simple name
  AZURE_WEBAPP_PACKAGE_PATH: '.'              # Set this to the path to your web app project

# IMPORTANT: Before this workflow works, you need to create a service principal and add these GitHub secrets:
# 1. AZURE_CREDENTIALS - Service principal JSON
# Run .\setup-github-actions.ps1 to create the service principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
